// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4ylSDdxk0F8XKni3tqAU5cWJeucqGxFk',
    appId: '1:990726513558:web:dc3b146d0ca70099dc33b7',
    messagingSenderId: '990726513558',
    projectId: 'flutter-course-chat-3fbb7',
    authDomain: 'flutter-course-chat-3fbb7.firebaseapp.com',
    storageBucket: 'flutter-course-chat-3fbb7.appspot.com',
    measurementId: 'G-L5R3L5T086',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4kdax2TQpl9Pm5NLZtxkG4jbbfzCQ7mY',
    appId: '1:990726513558:android:740187eb7573bbccdc33b7',
    messagingSenderId: '990726513558',
    projectId: 'flutter-course-chat-3fbb7',
    storageBucket: 'flutter-course-chat-3fbb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9jQh_JSrIaGFuUs1EUQ9gzIloLbhO3Rw',
    appId: '1:990726513558:ios:3ba593b1b7bea8bbdc33b7',
    messagingSenderId: '990726513558',
    projectId: 'flutter-course-chat-3fbb7',
    storageBucket: 'flutter-course-chat-3fbb7.appspot.com',
    iosClientId: '990726513558-p9lqmes77glgbrei0tpnrrdgn5vhj9i6.apps.googleusercontent.com',
    iosBundleId: 'com.xyz.chatcourseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9jQh_JSrIaGFuUs1EUQ9gzIloLbhO3Rw',
    appId: '1:990726513558:ios:243bcafac8b0d78ddc33b7',
    messagingSenderId: '990726513558',
    projectId: 'flutter-course-chat-3fbb7',
    storageBucket: 'flutter-course-chat-3fbb7.appspot.com',
    iosClientId: '990726513558-na1nkvqgmie95houss8fmfa4fkcboefr.apps.googleusercontent.com',
    iosBundleId: 'com.example.section8',
  );
}
